[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Mikołaj Nowak <miknowak@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
